# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chiperka < Formula
  desc "Declarative API & integration testing. Write YAML, run against real services."
  homepage "https://about.chiperka.com"
  version "1.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chiperka/chiperka/releases/download/1.5.1/chiperka_1.5.1_darwin_amd64.tar.gz"
      sha256 "04cc8eca907d1567152668545b379515d656582beff3dafb4389f292b59dcddd"

      define_method(:install) do
        bin.install "chiperka"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chiperka/chiperka/releases/download/1.5.1/chiperka_1.5.1_darwin_arm64.tar.gz"
      sha256 "cb44b6cb5027db0645cf6a2086682864ae4acb86102e39f944b87dd4d7b0ecf9"

      define_method(:install) do
        bin.install "chiperka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiperka/chiperka/releases/download/1.5.1/chiperka_1.5.1_linux_amd64.tar.gz"
      sha256 "55aeeaf6d45c9dc8d5b70acd4ab39605d4a49c9c08ce2736c5ee9e42431a46ff"
      define_method(:install) do
        bin.install "chiperka"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiperka/chiperka/releases/download/1.5.1/chiperka_1.5.1_linux_arm64.tar.gz"
      sha256 "39294947d60a23867fdebd827011218eeb16fb25b110b2604da2465e90896de8"
      define_method(:install) do
        bin.install "chiperka"
      end
    end
  end

  test do
    system "#{bin}/chiperka", "--version"
  end
end
