# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chiperka < Formula
  desc "Declarative API & integration testing. Write YAML, run against real services."
  homepage "https://about.chiperka.com"
  version "1.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chiperka/chiperka/releases/download/1.5.2/chiperka_1.5.2_darwin_amd64.tar.gz"
      sha256 "747a4dc6cbaf176d641effd9816dbd495c7fbf45e0bbed816b9ca45fbba2e461"

      define_method(:install) do
        bin.install "chiperka"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chiperka/chiperka/releases/download/1.5.2/chiperka_1.5.2_darwin_arm64.tar.gz"
      sha256 "ddcfd576f434f3de2b2156d2cf09c840f5bb89cb03a2e3718e70e3fbbf1abfec"

      define_method(:install) do
        bin.install "chiperka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiperka/chiperka/releases/download/1.5.2/chiperka_1.5.2_linux_amd64.tar.gz"
      sha256 "35777676c2b8a20ad2b98337be5685e8e1fa5c3387fbc61b43881ba3eceb95c8"
      define_method(:install) do
        bin.install "chiperka"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiperka/chiperka/releases/download/1.5.2/chiperka_1.5.2_linux_arm64.tar.gz"
      sha256 "3fd07e45ccadae4658ffe2e38a4ab9512a0bd36fc6466c266fadaa1a92827de8"
      define_method(:install) do
        bin.install "chiperka"
      end
    end
  end

  test do
    system "#{bin}/chiperka", "--version"
  end
end
