# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Declarative API & integration testing. Write YAML, run against real services."
  homepage "https://about.chiperka.com"
  version "1.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chiperka/cli/releases/download/1.6.1/cli_1.6.1_darwin_amd64.tar.gz"
      sha256 "c73a1f0d413691634dfbb05d25f512ec97dd2ff72693a13642c694129baeecbe"

      define_method(:install) do
        bin.install "chiperka"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chiperka/cli/releases/download/1.6.1/cli_1.6.1_darwin_arm64.tar.gz"
      sha256 "9f283d515f14768c603e1bc2577e59aca14de1e83723509e09afc501ba973aec"

      define_method(:install) do
        bin.install "chiperka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiperka/cli/releases/download/1.6.1/cli_1.6.1_linux_amd64.tar.gz"
      sha256 "b99c9a5c3409e0c6219acad71cf08149d8352f9db7421d9f86ee22cdf3098439"
      define_method(:install) do
        bin.install "chiperka"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiperka/cli/releases/download/1.6.1/cli_1.6.1_linux_arm64.tar.gz"
      sha256 "37bd3475e1002b6e408800e570e4c86c765361c48a51ed994595776d16b0fc20"
      define_method(:install) do
        bin.install "chiperka"
      end
    end
  end

  test do
    system "#{bin}/chiperka", "--version"
  end
end
