# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Declarative API & integration testing. Write YAML, run against real services."
  homepage "https://about.chiperka.com"
  version "1.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chiperka/cli/releases/download/1.9.2/cli_1.9.2_darwin_amd64.tar.gz"
      sha256 "749096da23e2d830ffce79544188ca4eb77f0d364fb7a847d368b7bfae473d9a"

      define_method(:install) do
        bin.install "chiperka"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chiperka/cli/releases/download/1.9.2/cli_1.9.2_darwin_arm64.tar.gz"
      sha256 "1336b291a02f60a592586bc1bf2ef8206b1ff2ea81ff683ef33e370490f45d85"

      define_method(:install) do
        bin.install "chiperka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiperka/cli/releases/download/1.9.2/cli_1.9.2_linux_amd64.tar.gz"
      sha256 "949e98e6f02c2994ff190d29317c8b639a20060d1b72db7cdf40974aec94580a"
      define_method(:install) do
        bin.install "chiperka"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiperka/cli/releases/download/1.9.2/cli_1.9.2_linux_arm64.tar.gz"
      sha256 "60c277fd74e247a72d8b87879e9e1973eac94e4aeb2ec6f054feffa8d43a48a8"
      define_method(:install) do
        bin.install "chiperka"
      end
    end
  end

  test do
    system "#{bin}/chiperka", "--version"
  end
end
